<?php

namespace App\Libs\Configs;


class KeyConfig {
	const CONST_KEY_SELL_PROCESS   = 'SELL_PROCESS';
	const CONST_SELL_CRITERIA      = 'SELL_CRITERIA';
	const CONST_QA_SELL_BUSINESS   = 'QA_SELL_BUSINESS';
	const CONST_BUSINESS_VALUATION = 'BUSINESS_VALUATION';


	const CONST_BUY_PROCESS      = 'BUY_PROCESS';
	const CONST_BUYER_GUAREANTEE = "BUYER_GUAREANTEE";
	const CONST_BUY_QA           = "BUY_QA";

	const CONST_START_UP  = 'START_UP';
}



    
